// ─────────────────────────────────────────────────────────────
// theme-mobile.js  —  Sizing tokens for phone-sized screens
// Covers: iPhone, Android phones (width < 768pt)
// ─────────────────────────────────────────────────────────────

export const DEVICE_SIZES = {
  // ── Splash / index ──────────────────────────────────────────
  splash: {
    logoSizeRatio: 0.52, // multiplied by screen width
    titleFontSize: 42,
    sub1FontSize: 17,
    sub2FontSize: 13,
  },

  // ── IntroCarousel ───────────────────────────────────────────
  carousel: {
    topHeightRatio: 0.28, // fraction of screen height
    botHeightRatio: 0.7,
    titleFontSize: 32,
    titleLineHeight: 39,
    subtitleFontSize: 15,
    skipFontSize: 15,
    nextFontSize: 18,
    getStartedFontSize: 16,
    dotHeight: 8,
    dotActiveWidth: 26,
    dotInactiveWidth: 8,
    bottomBarPaddingH: 26,
    bottomBarPaddingBottom_ios: 44,
    bottomBarPaddingBottom_android: 24,
    nextBtnPaddingH: 24,
    nextBtnPaddingV: 13,
    getStartedPaddingH: 32,
    getStartedPaddingV: 14,
    // Level badge mini
    badgeRingSize: 88,
    badgeInnerSize: 74,
    badgeLvlLabelSize: 10,
    badgeLvlNumSize: 28,
    badgeBarWidth: 78,
    badgeMarginV: 5,
    // Activity badge mini
    activityCardPaddingV: 14,
    activityCardPaddingH: 14,
    activityIconBoxSize: 60,
    activityIconSize: 38,
    activityLabelFontSize: 18,
    activityMarginV: 7,
    // Story card mini (width computed from HALF_W)
    storyCardMarginBottom: 12,
    storyCardTitleFontSize: 13,
    storyCardTitleLineHeight: 17,
    storyCardIntroFontSize: 10,
    storyCardIntroLineHeight: 14,
    storyDotSize: 10,
    storyConnectorWidth: 12,
    // Desc lines
    descLineFirstFontSize: 22,
    descLineFirstLineHeight: 30,
    descLineBodyFontSize: 16,
    descLineBodyLineHeight: 23,
    // Slide panel layout
    panelPaddingH: 22,
    panelPaddingTop_ios: 52,
    panelPaddingTop_android: 32,
    panelHalfPaddingV: 16,
    panelHalfPaddingBottom: 88,
    accentBarWidth: 44,
    accentBarHeight: 4,
    // S1 desc/vis split ratios
    s1DescRatio: 0.65,
    s1VisRatio: 0.35,
  },

  // ── AccountChoice ───────────────────────────────────────────
  accountChoice: {
    appNameFontSize: 38,
    appTaglineFontSize: 18,
    appTaglineLineHeight: 20,
    cardTitleFontSize: 16,
    cardSubFontSize: 14,
    cardSubLineHeight: 17,
    cardArrowFontSize: 26,
    cardIconSize: 24,
    cardIconBoxSize: 61,
    cardPadding: 18,
    cardBorderRadius: 20,
    dividerTextFontSize: 16,
    dividerMarginV: 18,
    footerFontSize: 14,
    footerLineHeight: 17,
    footerMarginTop: 36,
    innerPaddingTop_ios: 120,
    innerPaddingTop_android: 90,
    innerPaddingBottom_ios: 44,
    innerPaddingBottom_android: 28,
    logoMarginBottom: 44,
    backBtnSize: 40,
    backIconFontSize: 28,
  },

  // ── OnboardingScreen ────────────────────────────────────────
  onboarding: {
    progressPipHeight: 3,
    progressMarginBottom: 14,
    stepTagFontSize: 11,
    stepTagLetterSpacing: 1.5,
    stepTagMarginBottom: 5,
    stepHeadingFontSize: 22,
    stepHeadingLineHeight: 29,
    stepHeadingMarginBottom: 4,
    stepHintFontSize: 13,
    stepHintMarginBottom: 14,
    cardBorderRadius: 28,
    cardWidth: null, // computed: width - 32
    cardWidthOffset: 32,
    dialogueFontSize: 21,
    dialogueLineHeight: 30,
    dialoguePaddingTop: 16,
    dialoguePaddingBottom: 16,
    nameFontSize: 20,
    namePaddingH: 22,
    namePaddingV: 16,
    continueFontSize: 19,
    continuePaddingH: 40,
    continuePaddingV: 16,
    continueMarginTop: 22,
    ageBtnWidth: 82,
    ageBtnHeight: 92,
    ageBtnBorderRadius: 22,
    ageFontSize: 26,
    genderPaddingV: 26,
    genderEmojiFontSize: 52,
    genderLabelFontSize: 24,
    genderGap: 20,
    innerPaddingTop: "30%",
    containerMarginTop: "40%",
    backBtnSize: 40,
    backIconFontSize: 28,
  },

  // ── Login ────────────────────────────────────────────────────
  login: {
    birdSize: 150,
    birdMarginBottom: 15,
    titleFontSize: 38,
    subtitleFontSize: 16,
    subtitleMarginBottom: 20,
    primaryBtnPaddingV: 16,
    primaryBtnFontSize: 18,
    primaryBtnIconSize: 18,
    primaryBtnMarginBottom: 24,
    dividerMarginBottom: 24,
    dividerFontSize: 14,
    labelFontSize: 15,
    labelMarginBottom: 8,
    inputFontSize: 17,
    inputPadding: 14,
    loginBtnPaddingV: 15,
    loginBtnFontSize: 18,
    formCardPadding: 20,
    backBtnSize: 40,
    backIconFontSize: 28,
  },

  // ── Home ─────────────────────────────────────────────────────
  home: {
    // Header / layout
    headerHeight: 190,

    // Level badge
    levelBadgeRingSize: 82,
    levelBadgeInnerSize: 68,
    levelBadgeLabelFontSize: 8,
    levelBadgeLabelLetterSpacing: 2,
    levelBadgeNumberFontSize: 26,
    levelBadgeNumberLineHeight: 28,
    levelBadgeViewingDotFontSize: 6,
    levelBadgeBarWidth: 76,
    levelBadgeBarHeight: 6,
    levelBadgeBarMarginTop: 5,
    levelBadgeBarDotSize: 12,

    // Profile icon
    profileIconSize: 60,

    // Currency / side icons
    sideIconSize: 60,
    badgeMinWidth: 26,
    badgeHeight: 26,
    badgePaddingH: 6,
    badgeBorderRadius: 13,
    badgeFontSize: 11,
    badgeTop: -6,
    badgeRight: -6,

    // Side layout
    sideLayerLeft: 20,
    sideLayerRight: 20,
    sideLayerTop: 8,
    sideRowMarginBottom: 25,
    levelBadgeAnchorTop: 40,

    // Section titles
    sectionTitleFontSize: 20,
    sectionTitleMarginBottom: 4,
    sectionTaglineFontSize: 12,
    sectionTaglineMarginBottom: 10,

    // Game cards
    gameCardWidth: 160,
    gameCardHeight: 200,
    gameCardBorderRadius: 20,
    gameCardMarginRight: 14,
    gameCardTitleFontSize: 15,
    gameCardSubFontSize: 11,
    gameCardPlayBadgeSize: 32,
    gameCardPlayBadgeBorderRadius: 16,
    gameCardPlayBadgeFontSize: 11,
    gameCardTextPaddingH: 12,
    gameCardTextPaddingBottom: 14,

    // Access mode banner
    bannerMarginH: 15,
    bannerMarginBottom: 8,
    bannerBorderRadius: 14,
    bannerPaddingH: 14,
    bannerPaddingV: 10,
    bannerEmojiFontSize: 16,
    bannerTextFontSize: 12,
    bannerTextLineHeight: 17,
    bannerBtnBorderRadius: 10,
    bannerBtnPaddingH: 10,
    bannerBtnPaddingV: 5,
    bannerBtnFontSize: 11,

    // View-only locked state
    viewOnlyPaddingV: 60,
    viewOnlyPaddingH: 32,
    viewOnlyGap: 14,
    viewOnlyEmojiFontSize: 64,
    viewOnlyTitleFontSize: 22,
    viewOnlyTextFontSize: 14,
    viewOnlyTextLineHeight: 22,
    goCurrentBtnBorderRadius: 24,
    goCurrentBtnPaddingH: 28,
    goCurrentBtnPaddingV: 13,
    goCurrentBtnFontSize: 14,
    goCurrentBtnMarginTop: 4,

    // Tutorial overlay
    tutorialTooltipBorderRadius: 18,
    tutorialTooltipPaddingV: 16,
    tutorialTooltipPaddingH: 18,
    tutorialTooltipTitleFontSize: 19,
    tutorialTooltipTitleMarginBottom: 6,
    tutorialTooltipDescFontSize: 15,
    tutorialTooltipDescLineHeight: 20,
    tutorialTopBarTop_ios: 56,
    tutorialTopBarTop_android: 32,
    tutorialSkipPaddingH: 14,
    tutorialSkipPaddingV: 7,
    tutorialSkipFontSize: 13,
    tutorialDotSize: 6,
    tutorialDotBorderRadius: 3,
    tutorialDotActiveWidth: 18,
    tutorialNavBottom_ios: 44,
    tutorialNavBottom_android: 24,
    tutorialNavBtnPaddingH: 25,
    tutorialNavBtnPaddingV: 15,
    tutorialNavBtnBorderRadius: 14,
    tutorialNavBtnMinWidth: 100,
    tutorialNavBtnFontSize: 18,
    tutorialStepCounterFontSize: 15,

    // Background circles
    bgCircle1Size: 350,
    bgCircle1Top: -80,
    bgCircle1Right: -80,
    bgCircle2Size: 200,
    bgCircle2Bottom: 100,
    bgCircle2Left: -60,
    bgCircle3Size: 150,
    bgCircle3Bottom: 200,
    bgCircle3Right: -40,

    // Mini bird (game card mascot)
    miniBirdContainerHeight: 72,
    miniBirdBodyWidth: 68,
    miniBirdBodyHeight: 50,

    // Mini cat (game card mascot)
    miniCatContainerSize: 72,

    // Profile icon sizes (internal elements)
    profileIconOuterSize: 60,
    profileIconLetterFontSize: 10,
  },
  // ── MainStoryCard ─────────────────────────────────────────────
  mainStoryCard: {
    cardMaxWidth: 420,
    cardMarginHorizontal: 45,
    cardMarginVertical: 20,
    cardBorderRadius: 24,
    cardPaddingBottom: 15,

    // Image frame
    imageFrameMarginH: 16,
    imageFrameMarginTop: 16,
    imageFrameMarginBottom: 4,
    imageFrameBorderRadius: 16,
    imageFrameHeight: 180,

    // Title overlay
    titleFontSize: 20,
    titleLineHeight: 26,
    titleOverlayPaddingTop: 28,
    titleOverlayPaddingBottom: 12,
    titleOverlayPaddingH: 14,

    // Corner accents
    cornerSize: 16,
    cornerBorderWidth: 2.5,
    cornerBorderRadius: 4,
    cornerInset: 4,

    // NEW badge
    newBadgeTop: 10,
    newBadgeRight: 10,
    newBadgeBorderRadius: 8,
    newBadgePaddingH: 8,
    newBadgePaddingV: 3,
    newBadgeFontSize: 9,
    newBadgeLetterSpacing: 1.5,

    // Description
    descFontSize: 14,
    descLineHeight: 18,
    descPaddingH: 20,
    descPaddingTop: 12,
    descPaddingBottom: 10,

    // Steps row
    stepsRowMarginH: 14,
    stepsRowMarginBottom: 16,
    stepsRowGap: 8,
    stepCardHeight: 80,
    stepCardBorderRadius: 14,
    stepCardPaddingV: 10,
    stepCardPaddingH: 4,
    stepCardGap: 6,
    stepImageSize: 52,
    stepLabelFontSize: 12,
    stepLabelLetterSpacing: 0.2,
    checkBadgeTop: 6,
    checkBadgeRight: 6,
    checkBadgeSize: 18,
    checkBadgeFontSize: 10,
    activeDotBottom: 6,
    activeDotSize: 6,

    // Play button
    tapHintBorderRadius: 30,
    tapHintPaddingH: 36,
    tapHintPaddingV: 16,
    tapHintFontSize: 18,
    tapHintLetterSpacing: 1,
    tapHintMarginH: 20,
  },

  // ── StoryCard ─────────────────────────────────────────────────
  storyCard: {
    cardWidth: 175,
    cardHeight: 215,
    imageHeight: 135,
    cardMargin: 10,

    // Top-left badge
    topLeftBadgeSize: 34,
    topLeftBadgeBorderRadius: 17,
    topLeftBadgeOffset: -10,
    tickFontSize: 18,

    // Title
    titleFontSize: 16,
    titleLineHeight: 17,
    titlePaddingH: 10,
    titlePaddingBottom: 8,
    titlePaddingTop: 10,

    // Completed ribbon
    ribbonTop: 8,
    ribbonPaddingH: 8,
    ribbonPaddingV: 3,
    ribbonBorderRadius: 8,
    ribbonFontSize: 10,

    // Intro
    introFontSize: 12,
    introLineHeight: 14,
    introPaddingH: 10,
    introMarginTop: 8,
    introMarginBottom: 2,

    // Steps row
    stepsRowPaddingH: 8,
    stepsRowPaddingV: 7,
    stepsRowMarginH: 10,
    stepsRowBorderRadius: 20,
    stepIconWrapSize: 28,
    stepIconWrapBorderRadius: 6,
    stepIconWrapPadding: 2,
    stepImageSize: 20,
    stepDotSize: 4,
    stepDotMarginH: 3,

    // Resume label
    resumeLabelFontSize: 9,
    resumeLabelMarginTop: 4,
    resumeLabelMarginBottom: 2,
  },

  // ── Account screen ────────────────────────────────────────
  account: {
    // Option cards (top row)
    optionCardPaddingV: 22,
    optionCardPaddingH: 10,
    optionCardBorderRadius: 18,
    optionCardIconSize: 52,
    optionCardLabelFontSize: 13,
    optionCardGap: 10,
    optionCardRowGap: 10,
    optionSectionPaddingH: 20,
    optionSectionPaddingTop: 16,
    optionSectionPaddingBottom: 20,

    // "Who's Reading" title
    titleFontSize: 32,
    titleMarginTop: 16,
    titleMarginBottom: 8,

    // Current profile banner
    bannerPadding: 12,
    bannerMarginH: 20,
    bannerMarginTop: 16,
    bannerMarginBottom: 8,
    bannerBorderRadius: 10,
    bannerTextFontSize: 16,

    // Profiles list
    listPaddingH: 20,

    // Add button
    addBtnBorderRadius: 20,
    addBtnPadding: 20,
    addBtnMarginTop: 10,
    addBtnFontSize: 18,

    // Account section box
    accountSectionMarginH: 20,
    accountSectionMarginTop: 8,
    accountSectionMarginBottom: 24,
    accountSectionBorderRadius: 20,
    accountSectionPadding: 18,
    accountSectionIconFontSize: 20,
    accountSectionTitleFontSize: 18,
    accountSectionHeaderGap: 8,
    accountSectionHeaderMarginBottom: 16,

    // Credentials form
    credentialsHintFontSize: 13,
    credentialsHintLineHeight: 19,
    credentialsInputBorderRadius: 12,
    credentialsInputPadding: 14,
    credentialsInputFontSize: 15,
    credentialsBtnBorderRadius: 12,
    credentialsBtnPaddingV: 14,
    credentialsBtnFontSize: 15,

    // Email linked row
    emailLinkedRowBorderRadius: 12,
    emailLinkedRowPadding: 12,
    emailLinkedRowGap: 12,
    emailLinkedBadgeSize: 32,
    emailLinkedBadgeBorderRadius: 16,
    emailLinkedIconFontSize: 15,
    emailLinkedLabelFontSize: 11,
    emailLinkedValueFontSize: 14,

    // Logout
    logoutMarginH: 20,
    logoutMarginTop: 8,
    logoutPaddingV: 16,
    logoutBorderRadius: 16,
    logoutIconFontSize: 18,
    logoutTextFontSize: 16,
    logoutGap: 10,

    // Modal
    modalOverlayPadding: 20,
    modalBorderRadius: 25,
    modalPadding: 25,
    modalMaxWidth: 400,
    modalTitleFontSize: 26,
    modalTitleMarginBottom: 25,
    modalLabelFontSize: 16,
    modalLabelMarginBottom: 8,
    modalInputBorderRadius: 12,
    modalInputPadding: 15,
    modalInputFontSize: 16,
    modalInputGroupMarginBottom: 20,

    // Age buttons
    ageBtnSize: 42,
    ageBtnBorderRadius: 22,
    ageBtnFontSize: 16,
    ageSectionGap: 12,
    ageSectionMarginTop: 10,

    // Gender buttons
    genderBtnBorderRadius: 24,
    genderBtnPaddingV: 26,
    genderEmojiFontSize: 52,
    genderLabelFontSize: 24,
    genderSectionGap: 20,
    genderSectionMarginTop: 10,

    // Modal actions
    modalActionGap: 10,
    modalActionMarginTop: 20,
    actionBtnPaddingV: 15,
    actionBtnBorderRadius: 12,
    actionBtnFontSize: 16,
  },
  // ── Billing screens ───────────────────────────────────────
  billing: {
    headerPaddingH: 18,
    headerPaddingBottom: 14,
    backBtnSize: 38,
    backBtnBorderRadius: 19,
    backIconFontSize: 18,
    titleFontSize: 18,
    subtitleFontSize: 12,

    scrollPadding: 18,
    scrollPaddingTop: 20,

    // Plan card
    planCardBorderRadius: 20,
    planCardPadding: 18,
    planCardMarginBottom: 20,
    planLabelFontSize: 10,
    planNameFontSize: 26,
    planPriceFontSize: 15,
    statusBadgeBorderRadius: 10,
    statusBadgePaddingH: 10,
    statusBadgePaddingV: 4,
    statusTextFontSize: 11,
    nextBillingFontSize: 12,
    upgradeBtnBorderRadius: 12,
    upgradeBtnPaddingV: 12,
    upgradeBtnFontSize: 14,

    // Section cards
    sectionBorderRadius: 16,
    sectionPadding: 16,
    sectionMarginBottom: 16,
    sectionTitleFontSize: 13,
    sectionLinkFontSize: 12,

    // Card chip
    cardChipWidth: 44,
    cardChipHeight: 30,
    cardChipBorderRadius: 6,
    cardChipFontSize: 8,
    cardNumFontSize: 14,
    cardExpFontSize: 11,
    defaultBadgeFontSize: 10,
    defaultBadgeBorderRadius: 8,
    defaultBadgePaddingH: 8,
    defaultBadgePaddingV: 3,

    addCardBtnPaddingV: 14,
    addCardBtnBorderRadius: 12,
    addCardFontSize: 13,

    historyHintFontSize: 12,
    historyHintBorderRadius: 10,
    historyHintPadding: 12,

    // Subscription plans screen
    planCardWidth: 0.8, // fraction of SW
    planCardMargin: 14,
    planCardBorderRadius2: 28,
    planCardPaddingH: 20,
    planCardPaddingTop: 28,
    planCardPaddingBottom: 26,
    planIconWrapperSize: 112,
    planIconOuterRing: 112,
    planIconInnerRing: 84,
    planIconCircle: 64,
    planIconEmojiFontSize: 28,
    planNameFontSize2: 26,
    planTaglineFontSize: 13,
    planDescFontSize: 12,
    planDescLineHeight: 18,
    planPriceMainFontSize: 34,
    planPriceSubFontSize: 14,
    planPriceBorderRadius: 16,
    planPricePaddingV: 10,
    planPricePaddingH: 22,
    featureRowBorderRadius: 12,
    featureRowPaddingV: 9,
    featureRowPaddingH: 12,
    featureRowMarginBottom: 6,
    featureIconWrapSize: 30,
    featureIconFontSize: 14,
    featureLabelFontSize: 12,
    featureCheckFontSize: 12,
    ctaBtnHeight: 52,
    ctaBtnBorderRadius: 27,
    ctaEmojiFontSize: 17,
    ctaTextFontSize: 15,
    currentPlanBadgeBorderRadius: 10,
    currentPlanBadgePaddingH: 14,
    currentPlanBadgePaddingV: 5,
    currentPlanBadgeFontSize: 11,
    currentPlanBadgeMarginBottom: 12,
    trialNoteFontSize: 11,
    swipeHintFontSize: 12,
    cycleToggleBorderRadius: 18,
    cycleTogglePillBorderRadius: 14,
    cycleTogglePillPaddingV: 11,
    cycleToggleFontSize: 12,
    cycleBadgeFontSize: 8,
    paginationDotSize: 6,
    paginationDotActiveWidth: 22,

    // Payment method screen
    cardItemBorderRadius: 16,
    cardItemPadding: 16,
    cardItemMarginBottom: 12,
    menuBtnSize: 32,
    menuDotsFontSize: 20,
    actionItemPaddingV: 12,
    actionItemPaddingH: 14,
    actionItemFontSize: 13,
    addMethodBtnBorderRadius: 14,
    addMethodBtnPaddingV: 16,
    addMethodIconFontSize: 20,
    addMethodFontSize: 14,

    // Add card modal
    modalSheetBorderRadius: 24,
    modalSheetPadding: 24,
    modalSheetTitleFontSize: 18,
    modalSheetSubtitleFontSize: 12,
    modalSheetLabelFontSize: 11,
    modalSheetInputBorderRadius: 12,
    modalSheetInputPadding: 14,
    modalSheetInputFontSize: 15,
    modalSheetBrandBtnPaddingH: 14,
    modalSheetBrandBtnPaddingV: 8,
    modalSheetBrandBtnBorderRadius: 10,
    modalSheetBrandFontSize: 12,
    modalSheetActionPaddingV: 14,
    modalSheetActionBorderRadius: 12,
    modalSheetActionFontSize: 14,
    modalHandleWidth: 40,
    modalHandleHeight: 4,

    // Billing history
    summaryCardBorderRadius: 16,
    summaryCardPadding: 16,
    summaryCardMarginBottom: 20,
    summaryValFontSize: 18,
    summaryLblFontSize: 9,
    listCardBorderRadius: 16,
    listCardPadding: 16,
    listLabelFontSize: 11,
    invoiceRowPaddingV: 14,
    invoiceRowGap: 12,
    invoiceDateFontSize: 11,
    invoiceDescFontSize: 13,
    invoiceAmountFontSize: 15,
    statusBadgeRowPaddingH: 8,
    statusBadgeRowPaddingV: 2,
    statusBadgeRowBorderRadius: 7,
    statusBadgeRowFontSize: 9,
    downloadLinkFontSize: 10,
    emptyIconFontSize: 48,
    emptyTitleFontSize: 18,
    emptySubtitleFontSize: 13,

    // ── BillingHistoryScreen ─────────────────────
    historyHeaderPaddingH: 18,
    historyHeaderPaddingBottom: 14,
    historyBackBtnSize: 38,
    historyBackBtnBorderRadius: 19,
    historyBackIconFontSize: 18,
    historyTitleFontSize: 18,
    historyScrollPadding: 18,
    historySummaryCardBorderRadius: 16,
    historySummaryCardPadding: 16,
    historySummaryCardMarginBottom: 20,
    historySummaryValFontSize: 18,
    historySummaryLblFontSize: 9,
    historyListCardBorderRadius: 16,
    historyListCardPadding: 16,
    historyListLabelFontSize: 11,
    historyRowPaddingV: 14,
    historyRowGap: 12,
    historyDateFontSize: 11,
    historyDescFontSize: 13,
    historyAmountFontSize: 15,
    historyStatusBadgePaddingH: 8,
    historyStatusBadgePaddingV: 2,
    historyStatusBadgeBorderRadius: 7,
    historyStatusFontSize: 9,
    historyDownloadFontSize: 10,
    historyEmptyPaddingV: 60,
    historyEmptyIconFontSize: 48,
    historyEmptyTitleFontSize: 18,
    historyEmptySubFontSize: 13,

    // ── LevelSelectScreen ────────────────────────
    levelHeaderPaddingH: 18,
    levelHeaderPaddingBottom: 16,
    levelBackBtnSize: 40,
    levelBackBtnBorderRadius: 20,
    levelBackIconFontSize: 18,
    levelHeaderTitleFontSize: 18,
    levelScrollPadding: 20,
    levelIntroBoxBorderRadius: 18,
    levelIntroBoxPadding: 20,
    levelIntroBoxMarginBottom: 24,
    levelIntroBoxGap: 8,
    levelIntroEmojiFontSize: 40,
    levelIntroTitleFontSize: 17,
    levelIntroTitleLineHeight: 24,
    levelIntroSubFontSize: 12,
    levelIntroSubLineHeight: 18,
    levelGridGap: 10,
    levelGridMarginBottom: 20,
    levelCardBorderRadius: 14,
    levelCardNumberFontSize: 22,
    levelSelectedDotSize: 7,
    levelSelectedDotBorderRadius: 3.5,
    levelCalloutBorderRadius: 16,
    levelCalloutPadding: 16,
    levelCalloutMarginBottom: 24,
    levelCalloutGap: 4,
    levelCalloutLabelFontSize: 10,
    levelCalloutLevelFontSize: 40,
    levelCalloutLevelLineHeight: 48,
    levelCalloutDescFontSize: 13,
    levelConfirmBtnHeight: 54,
    levelConfirmBtnBorderRadius: 27,
    levelConfirmTextFontSize: 16,

    // ── PaymentMethodScreen ──────────────────────
    paymentCardBorderRadius: 16,
    paymentCardPadding: 16,
    paymentCardMarginBottom: 12,
    paymentChipWidth: 44,
    paymentChipHeight: 30,
    paymentChipBorderRadius: 6,
    paymentChipFontSize: 8,
    paymentCardNumFontSize: 14,
    paymentCardExpFontSize: 11,
    paymentMenuBtnSize: 32,
    paymentMenuDotsFontSize: 20,
    paymentDefaultBadgeBorderRadius: 8,
    paymentDefaultBadgePaddingH: 10,
    paymentDefaultBadgePaddingV: 3,
    paymentDefaultBadgeFontSize: 10,
    paymentActionMenuBorderRadius: 10,
    paymentActionItemPaddingV: 12,
    paymentActionItemPaddingH: 14,
    paymentActionItemFontSize: 13,
    paymentAddBtnBorderRadius: 14,
    paymentAddBtnPaddingV: 16,
    paymentAddBtnIconFontSize: 20,
    paymentAddBtnFontSize: 14,
    paymentEmptyPaddingV: 48,
    paymentEmptyIconFontSize: 48,
    paymentEmptyTitleFontSize: 18,
    paymentEmptySubFontSize: 13,
    // Add card modal
    paymentModalHandleWidth: 40,
    paymentModalHandleHeight: 4,
    paymentModalBorderRadius: 24,
    paymentModalPadding: 24,
    paymentModalTitleFontSize: 18,
    paymentModalSubFontSize: 12,
    paymentModalLabelFontSize: 11,
    paymentModalInputBorderRadius: 12,
    paymentModalInputPadding: 14,
    paymentModalInputFontSize: 15,
    paymentModalBrandBtnPaddingH: 14,
    paymentModalBrandBtnPaddingV: 8,
    paymentModalBrandBtnBorderRadius: 10,
    paymentModalBrandFontSize: 12,
    paymentModalActionPaddingV: 14,
    paymentModalActionBorderRadius: 12,
    paymentModalActionFontSize: 14,

    // ── PurchaseScreen ───────────────────────────
    purchaseHeaderPaddingH: 18,
    purchaseHeaderPaddingBottom: 16,
    purchaseBackBtnSize: 40,
    purchaseBackBtnBorderRadius: 20,
    purchaseBackIconFontSize: 18,
    purchaseHeaderTitleFontSize: 18,
    purchaseScrollPadding: 20,
    purchaseSectionLabelFontSize: 13,
    purchaseSectionLabelMarginBottom: 10,
    purchaseOrderCardBorderRadius: 20,
    purchaseOrderCardPadding: 18,
    purchaseOrderCardMarginBottom: 24,
    purchasePlanIconSize: 52,
    purchasePlanIconBorderRadius: 26,
    purchasePlanIconEmojiFontSize: 24,
    purchasePlanNameFontSize: 20,
    purchasePlanTaglineFontSize: 14,
    purchasePlanDescFontSize: 14,
    purchasePlanDescLineHeight: 18,
    purchasePricePillBorderRadius: 12,
    purchasePricePillPaddingV: 8,
    purchasePricePillPaddingH: 16,
    purchasePriceAmountFontSize: 28,
    purchasePriceCycleFontSize: 13,
    purchaseFeatureCheckFontSize: 14,
    purchaseFeatureLabelFontSize: 12,
    purchaseFeatureRowGap: 8,
    purchaseFeatureRowMarginBottom: 5,
    purchaseNoCardBorderRadius: 16,
    purchaseNoCardPadding: 24,
    purchaseNoCardGap: 8,
    purchaseNoCardIconFontSize: 40,
    purchaseNoCardTitleFontSize: 16,
    purchaseNoCardSubFontSize: 13,
    purchaseAddCardBtnBorderRadius: 12,
    purchaseAddCardBtnPaddingH: 28,
    purchaseAddCardBtnPaddingV: 12,
    purchaseAddCardBtnFontSize: 14,
    purchaseCardListBorderRadius: 16,
    purchaseCardRowPadding: 16,
    purchaseRadioSize: 20,
    purchaseRadioInnerSize: 10,
    purchaseCardNumFontSize: 14,
    purchaseCardExpFontSize: 11,
    purchaseDefaultBadgeBorderRadius: 8,
    purchaseDefaultBadgePaddingH: 8,
    purchaseDefaultBadgePaddingV: 3,
    purchaseDefaultBadgeFontSize: 10,
    purchaseAddAnotherPaddingV: 14,
    purchaseAddAnotherFontSize: 13,
    purchaseTotalCardBorderRadius: 14,
    purchaseTotalCardPadding: 16,
    purchaseTotalCardMarginBottom: 12,
    purchaseTotalLabelFontSize: 15,
    purchaseTotalAmountFontSize: 26,
    purchaseTotalCycleFontSize: 11,
    purchasePolicyFontSize: 11,
    purchasePolicyLineHeight: 18,
    purchasePolicyMarginBottom: 24,
    purchaseCheckoutBtnHeight: 56,
    purchaseCheckoutBtnBorderRadius: 27,
    purchaseCheckoutEmojiFontSize: 18,
    purchaseCheckoutTextFontSize: 16,
    // Add card sheet (same sheet pattern as PaymentMethod)
    purchaseSheetBorderRadius: 24,
    purchaseSheetPadding: 24,
    purchaseSheetTitleFontSize: 18,
    purchaseSheetSubFontSize: 12,
    purchaseSheetLabelFontSize: 11,
    purchaseSheetInputBorderRadius: 12,
    purchaseSheetInputPadding: 14,
    purchaseSheetInputFontSize: 15,
    purchaseSheetBrandPaddingH: 14,
    purchaseSheetBrandPaddingV: 8,
    purchaseSheetBrandBorderRadius: 10,
    purchaseSheetBrandFontSize: 12,
    purchaseSheetActionPaddingV: 14,
    purchaseSheetActionBorderRadius: 12,
    purchaseSheetActionFontSize: 14,
    purchaseSheetHandleWidth: 40,
    purchaseSheetHandleHeight: 4,
  },

  // ── Learning Path screen ──────────────────────────────────
  learningPath: {
    cardWidth: 0.45, // fraction of SW
    cardHeight: 200,
    connectorHeight: 60,
    screenPad: 16,

    // Card internals
    cardBorderRadius: 18,
    cardPaddingTop: 12,
    cardPaddingH: 12,
    cardPaddingBottom: 10,
    lvlBadgeSize: 34,
    lvlBadgeBorderRadius: 10,
    lvlNumFontSize: 15,
    emojiFontSize: 20,
    gradeFontSize: 12,
    gradeLineHeight: 16,
    gradeMarginBottom: 4,
    statFontSize: 10,
    statMarginBottom: 5,
    skillFontSize: 10,
    skillLineHeight: 14,
    youBadgeBorderRadius: 6,
    youBadgePaddingV: 4,
    youTxtFontSize: 8,
    youTxtLetterSpacing: 1,

    // Header
    backBtnSize: 38,
    backBtnBorderRadius: 19,
    backIconFontSize: 18,
    titleFontSize: 19,
    subtitleFontSize: 11,
    lvlPillBorderRadius: 10,
    lvlPillPaddingH: 10,
    lvlPillPaddingV: 5,
    lvlPillFontSize: 11,

    // Strip
    stripPaddingV: 10,
    stripValFontSize: 15,
    stripLblFontSize: 9,
    stripDivHeight: 28,

    // End cap
    endCapPaddingV: 28,
    endCapFontSize: 12,
  },

  // ── Reports screen ────────────────────────────────────────
  reports: {
    scrollPaddingH: 16,
    scrollPaddingBottom: 24,

    // Top bar
    topBarPaddingH: 14,
    topBarPaddingBottom: 12,
    backBtnSize: 40,
    backBtnBorderRadius: 20,
    topTitleFontSize: 17,

    // Child header
    childAvatarSize: 52,
    childAvatarBorderRadius: 26,
    childAvatarFontSize: 22,
    childNameFontSize: 20,
    childLevelFontSize: 12,
    childHeaderGap: 14,
    childHeaderMarginBottom: 20,

    // Stat pills
    pillBorderRadius: 16,
    pillPaddingV: 14,
    pillPaddingH: 6,
    pillGap: 4,
    pillRowGap: 8,
    pillRowMarginBottom: 14,
    pillEmojiFontSize: 20,
    pillValueFontSize: 19,
    pillLabelFontSize: 9,

    // Section card
    sectionCardBorderRadius: 20,
    sectionCardPadding: 18,
    sectionCardMarginBottom: 14,
    sectionIconFontSize: 18,
    sectionTitleFontSize: 15,
    sectionHeaderGap: 8,
    sectionHeaderMarginBottom: 16,

    // Ring chart
    ringChartSize: 148,
    ringLegendPaddingLeft: 18,
    ringLegendGap: 14,
    legendDotSize: 10,
    legendLabelFontSize: 11,
    legendValueFontSize: 13,

    // Weekly bar chart
    barChartHeight: 90,
    barCountFontSize: 10,
    barWeekLabelFontSize: 9,

    // Skill bars
    skillIconSize: 26,
    skillLabelFontSize: 13,
    skillPctFontSize: 13,
    skillTrackHeight: 8,
    skillRowGap: 12,
    skillRowMarginBottom: 16,

    // Story rows
    statusDotSize: 8,
    storyTitleFontSize: 13,
    storyDateFontSize: 11,
    storyDotSize: 10,
    storyDotGap: 5,
    storyRowGap: 12,
    storyRowPaddingV: 12,

    // Chart subtitle
    chartSubFontSize: 11,
    chartSubMarginBottom: 12,

    // Story legend
    storyLegendGap: 14,
    storyLegendItemGap: 5,
    storyLegendDotSize: 8,

    // Loading / empty states
    loadingEmojiFontSize: 48,
    loadingTextFontSize: 15,
    retryBtnBorderRadius: 12,
    retryBtnPaddingH: 24,
    retryBtnPaddingV: 10,
    retryTextFontSize: 14,
    emptyEmojiFontSize: 56,
    emptyTitleFontSize: 20,
    emptyTextFontSize: 14,
    emptyTextLineHeight: 21,
    emptyWrapPaddingV: 60,
    emptyWrapGap: 12,
  },
};
