// ─────────────────────────────────────────────────────────────
// theme-tablet.js  —  Sizing tokens for tablet-sized screens
// Covers: iPad, Android tablets (width >= 768pt)
// ─────────────────────────────────────────────────────────────

export const DEVICE_SIZES = {
  // ── Splash / index ──────────────────────────────────────────
  splash: {
    logoSizeRatio: 0.32, // smaller ratio — tablet screens are huge
    titleFontSize: 58,
    sub1FontSize: 24,
    sub2FontSize: 18,
  },

  // ── IntroCarousel ───────────────────────────────────────────
  carousel: {
    topHeightRatio: 0.25, // slightly less top on tablet (more vertical space)
    botHeightRatio: 0.75,
    titleFontSize: 44,
    titleLineHeight: 54,
    subtitleFontSize: 20,
    skipFontSize: 18,
    nextFontSize: 22,
    getStartedFontSize: 22,
    dotHeight: 10,
    dotActiveWidth: 34,
    dotInactiveWidth: 10,
    bottomBarPaddingH: 40,
    bottomBarPaddingBottom_ios: 48,
    bottomBarPaddingBottom_android: 32,
    nextBtnPaddingH: 36,
    nextBtnPaddingV: 18,
    getStartedPaddingH: 48,
    getStartedPaddingV: 20,
    // Level badge mini
    badgeRingSize: 120,
    badgeInnerSize: 102,
    badgeLvlLabelSize: 13,
    badgeLvlNumSize: 38,
    badgeBarWidth: 106,
    badgeMarginV: 8,
    // Activity badge mini
    activityCardPaddingV: 20,
    activityCardPaddingH: 20,
    activityIconBoxSize: 80,
    activityIconSize: 52,
    activityLabelFontSize: 24,
    activityMarginV: 12,
    // Story card mini
    storyCardMarginBottom: 16,
    storyCardTitleFontSize: 27,
    storyCardTitleLineHeight: 27,
    storyCardIntroFontSize: 18,
    storyCardIntroLineHeight: 22,
    storyDotSize: 13,
    storyConnectorWidth: 16,
    // Desc lines
    descLineFirstFontSize: 30,
    descLineFirstLineHeight: 40,
    descLineBodyFontSize: 22,
    descLineBodyLineHeight: 31,
    // Slide panel layout
    panelPaddingH: 36,
    panelPaddingTop_ios: 64,
    panelPaddingTop_android: 44,
    panelHalfPaddingV: 24,
    panelHalfPaddingBottom: 110,
    accentBarWidth: 60,
    accentBarHeight: 5,
    // S1 desc/vis split ratios
    s1DescRatio: 0.6,
    s1VisRatio: 0.4,
  },

  // ── AccountChoice ───────────────────────────────────────────
  accountChoice: {
    appNameFontSize: 52,
    appTaglineFontSize: 24,
    appTaglineLineHeight: 30,
    cardTitleFontSize: 22,
    cardSubFontSize: 18,
    cardSubLineHeight: 24,
    cardArrowFontSize: 34,
    cardIconSize: 32,
    cardIconBoxSize: 72,
    cardPadding: 26,
    cardBorderRadius: 28,
    dividerTextFontSize: 20,
    dividerMarginV: 26,
    footerFontSize: 18,
    footerLineHeight: 24,
    footerMarginTop: 48,
    innerPaddingTop_ios: 160,
    innerPaddingTop_android: 120,
    innerPaddingBottom_ios: 60,
    innerPaddingBottom_android: 40,
    logoMarginBottom: 60,
    backBtnSize: 52,
    backIconFontSize: 36,
  },

  // ── OnboardingScreen ────────────────────────────────────────
  onboarding: {
    progressPipHeight: 4,
    progressMarginBottom: 20,
    stepTagFontSize: 14,
    stepTagLetterSpacing: 2,
    stepTagMarginBottom: 8,
    stepHeadingFontSize: 32,
    stepHeadingLineHeight: 42,
    stepHeadingMarginBottom: 6,
    stepHintFontSize: 18,
    stepHintMarginBottom: 20,
    cardBorderRadius: 36,
    cardWidth: null, // computed: width - 64
    cardWidthOffset: 64,
    dialogueFontSize: 28,
    dialogueLineHeight: 40,
    dialoguePaddingTop: 24,
    dialoguePaddingBottom: 24,
    nameFontSize: 26,
    namePaddingH: 28,
    namePaddingV: 22,
    continueFontSize: 24,
    continuePaddingH: 60,
    continuePaddingV: 22,
    continueMarginTop: 30,
    ageBtnWidth: 110,
    ageBtnHeight: 120,
    ageBtnBorderRadius: 28,
    ageFontSize: 34,
    genderPaddingV: 46,
    genderEmojiFontSize: 70,
    genderLabelFontSize: 30,
    genderGap: 30,
    innerPaddingTop: "20%",
    containerMarginTop: "30%",
    backBtnSize: 52,
    backIconFontSize: 36,
  },

  // ── Login ────────────────────────────────────────────────────
  login: {
    birdSize: 200,
    birdMarginBottom: 24,
    titleFontSize: 52,
    subtitleFontSize: 22,
    subtitleMarginBottom: 30,
    primaryBtnPaddingV: 22,
    primaryBtnFontSize: 24,
    primaryBtnIconSize: 26,
    primaryBtnMarginBottom: 36,
    dividerMarginBottom: 36,
    dividerFontSize: 18,
    labelFontSize: 20,
    labelMarginBottom: 12,
    inputFontSize: 22,
    inputPadding: 20,
    loginBtnPaddingV: 22,
    loginBtnFontSize: 24,
    formCardPadding: 32,
    backBtnSize: 52,
    backIconFontSize: 36,
  },

  // ── Home ─────────────────────────────────────────────────────
  home: {
    // Header / layout
    headerHeight: 260,

    // Level badge
    levelBadgeRingSize: 110,
    levelBadgeInnerSize: 92,
    levelBadgeLabelFontSize: 11,
    levelBadgeLabelLetterSpacing: 2.5,
    levelBadgeNumberFontSize: 36,
    levelBadgeNumberLineHeight: 38,
    levelBadgeViewingDotFontSize: 8,
    levelBadgeBarWidth: 102,
    levelBadgeBarHeight: 8,
    levelBadgeBarMarginTop: 7,
    levelBadgeBarDotSize: 16,

    // Profile icon
    profileIconSize: 80,

    // Currency / side icons
    sideIconSize: 80,
    badgeMinWidth: 34,
    badgeHeight: 34,
    badgePaddingH: 8,
    badgeBorderRadius: 17,
    badgeFontSize: 14,
    badgeTop: -8,
    badgeRight: -8,

    // Side layout
    sideLayerLeft: 28,
    sideLayerRight: 28,
    sideLayerTop: 12,
    sideRowMarginBottom: 32,
    levelBadgeAnchorTop: 52,

    // Section titles
    sectionTitleFontSize: 28,
    sectionTitleMarginBottom: 6,
    sectionTaglineFontSize: 16,
    sectionTaglineMarginBottom: 14,

    // Game cards
    gameCardWidth: 220,
    gameCardHeight: 270,
    gameCardBorderRadius: 26,
    gameCardMarginRight: 20,
    gameCardTitleFontSize: 20,
    gameCardSubFontSize: 15,
    gameCardPlayBadgeSize: 44,
    gameCardPlayBadgeBorderRadius: 22,
    gameCardPlayBadgeFontSize: 15,
    gameCardTextPaddingH: 16,
    gameCardTextPaddingBottom: 20,

    // Access mode banner
    bannerMarginH: 22,
    bannerMarginBottom: 12,
    bannerBorderRadius: 18,
    bannerPaddingH: 20,
    bannerPaddingV: 14,
    bannerEmojiFontSize: 22,
    bannerTextFontSize: 16,
    bannerTextLineHeight: 23,
    bannerBtnBorderRadius: 14,
    bannerBtnPaddingH: 14,
    bannerBtnPaddingV: 8,
    bannerBtnFontSize: 14,

    // View-only locked state
    viewOnlyPaddingV: 80,
    viewOnlyPaddingH: 52,
    viewOnlyGap: 20,
    viewOnlyEmojiFontSize: 88,
    viewOnlyTitleFontSize: 30,
    viewOnlyTextFontSize: 18,
    viewOnlyTextLineHeight: 28,
    goCurrentBtnBorderRadius: 30,
    goCurrentBtnPaddingH: 40,
    goCurrentBtnPaddingV: 18,
    goCurrentBtnFontSize: 18,
    goCurrentBtnMarginTop: 8,

    // Tutorial overlay
    tutorialTooltipBorderRadius: 24,
    tutorialTooltipPaddingV: 22,
    tutorialTooltipPaddingH: 26,
    tutorialTooltipTitleFontSize: 22,
    tutorialTooltipTitleMarginBottom: 10,
    tutorialTooltipDescFontSize: 18,
    tutorialTooltipDescLineHeight: 28,
    tutorialTopBarTop_ios: 68,
    tutorialTopBarTop_android: 44,
    tutorialSkipPaddingH: 20,
    tutorialSkipPaddingV: 10,
    tutorialSkipFontSize: 17,
    tutorialDotSize: 8,
    tutorialDotBorderRadius: 4,
    tutorialDotActiveWidth: 26,
    tutorialNavBottom_ios: 56,
    tutorialNavBottom_android: 36,
    tutorialNavBtnPaddingH: 36,
    tutorialNavBtnPaddingV: 20,
    tutorialNavBtnBorderRadius: 18,
    tutorialNavBtnMinWidth: 140,
    tutorialNavBtnFontSize: 24,
    tutorialStepCounterFontSize: 17,

    // Background circles
    bgCircle1Size: 500,
    bgCircle1Top: -120,
    bgCircle1Right: -120,
    bgCircle2Size: 300,
    bgCircle2Bottom: 140,
    bgCircle2Left: -80,
    bgCircle3Size: 220,
    bgCircle3Bottom: 280,
    bgCircle3Right: -60,

    // Mini bird (game card mascot)
    miniBirdContainerHeight: 100,
    miniBirdBodyWidth: 94,
    miniBirdBodyHeight: 70,

    // Mini cat (game card mascot)
    miniCatContainerSize: 100,

    // Profile icon sizes (internal elements)
    profileIconOuterSize: 80,
    profileIconLetterFontSize: 14,
  },
  // ── MainStoryCard ─────────────────────────────────────────────
  mainStoryCard: {
    cardMaxWidth: 680,
    cardMarginHorizontal: 60,
    cardMarginVertical: 28,
    cardBorderRadius: 32,
    cardPaddingBottom: 28,

    // Image frame
    imageFrameMarginH: 22,
    imageFrameMarginTop: 22,
    imageFrameMarginBottom: 6,
    imageFrameBorderRadius: 22,
    imageFrameHeight: 260,

    // Title overlay
    titleFontSize: 28,
    titleLineHeight: 36,
    titleOverlayPaddingTop: 36,
    titleOverlayPaddingBottom: 18,
    titleOverlayPaddingH: 20,

    // Corner accents
    cornerSize: 22,
    cornerBorderWidth: 3,
    cornerBorderRadius: 6,
    cornerInset: 6,

    // NEW badge
    newBadgeTop: 14,
    newBadgeRight: 14,
    newBadgeBorderRadius: 11,
    newBadgePaddingH: 12,
    newBadgePaddingV: 5,
    newBadgeFontSize: 12,
    newBadgeLetterSpacing: 1.8,

    // Description
    descFontSize: 16,
    descLineHeight: 24,
    descPaddingH: 28,
    descPaddingTop: 18,
    descPaddingBottom: 14,

    // Steps row
    stepsRowMarginH: 20,
    stepsRowMarginBottom: 22,
    stepsRowGap: 12,
    stepCardHeight: 140,
    stepCardBorderRadius: 20,
    stepCardPaddingV: 14,
    stepCardPaddingH: 6,
    stepCardGap: 10,
    stepImageSize: 72,
    stepLabelFontSize: 15,
    stepLabelLetterSpacing: 0.3,
    checkBadgeTop: 8,
    checkBadgeRight: 8,
    checkBadgeSize: 26,
    checkBadgeFontSize: 14,
    activeDotBottom: 8,
    activeDotSize: 9,

    // Play button
    tapHintBorderRadius: 36,
    tapHintPaddingH: 52,
    tapHintPaddingV: 22,
    tapHintFontSize: 24,
    tapHintLetterSpacing: 1.5,
    tapHintMarginH: 28,
  },

  // ── StoryCard ─────────────────────────────────────────────────
  storyCard: {
    cardWidth: 250,
    cardHeight: 340,
    imageHeight: 190,
    cardMargin: 14,

    // Top-left badge
    topLeftBadgeSize: 46,
    topLeftBadgeBorderRadius: 23,
    topLeftBadgeOffset: -14,
    tickFontSize: 24,

    // Title
    titleFontSize: 17,
    titleLineHeight: 23,
    titlePaddingH: 14,
    titlePaddingBottom: 12,
    titlePaddingTop: 14,

    // Completed ribbon
    ribbonTop: 12,
    ribbonPaddingH: 12,
    ribbonPaddingV: 5,
    ribbonBorderRadius: 11,
    ribbonFontSize: 13,

    // Intro
    introFontSize: 13,
    introLineHeight: 19,
    introPaddingH: 14,
    introMarginTop: 12,
    introMarginBottom: 4,

    // Steps row
    stepsRowPaddingH: 12,
    stepsRowPaddingV: 10,
    stepsRowMarginH: 14,
    stepsRowBorderRadius: 26,
    stepIconWrapSize: 40,
    stepIconWrapBorderRadius: 9,
    stepIconWrapPadding: 3,
    stepImageSize: 28,
    stepDotSize: 6,
    stepDotMarginH: 5,

    // Resume label
    resumeLabelFontSize: 12,
    resumeLabelMarginTop: 6,
    resumeLabelMarginBottom: 4,
  },
  // ── Account screen ────────────────────────────────────────
  account: {
    // Option cards (top row)
    optionCardPaddingV: 30,
    optionCardPaddingH: 14,
    optionCardBorderRadius: 24,
    optionCardIconSize: 72,
    optionCardLabelFontSize: 17,
    optionCardGap: 14,
    optionCardRowGap: 14,
    optionSectionPaddingH: 28,
    optionSectionPaddingTop: 22,
    optionSectionPaddingBottom: 28,

    // "Who's Reading" title
    titleFontSize: 44,
    titleMarginTop: 22,
    titleMarginBottom: 12,

    // Current profile banner
    bannerPadding: 16,
    bannerMarginH: 28,
    bannerMarginTop: 22,
    bannerMarginBottom: 12,
    bannerBorderRadius: 14,
    bannerTextFontSize: 20,

    // Profiles list
    listPaddingH: 28,

    // Add button
    addBtnBorderRadius: 26,
    addBtnPadding: 28,
    addBtnMarginTop: 14,
    addBtnFontSize: 24,

    // Account section box
    accountSectionMarginH: 28,
    accountSectionMarginTop: 12,
    accountSectionMarginBottom: 32,
    accountSectionBorderRadius: 28,
    accountSectionPadding: 26,
    accountSectionIconFontSize: 28,
    accountSectionTitleFontSize: 24,
    accountSectionHeaderGap: 12,
    accountSectionHeaderMarginBottom: 22,

    // Credentials form
    credentialsHintFontSize: 17,
    credentialsHintLineHeight: 26,
    credentialsInputBorderRadius: 16,
    credentialsInputPadding: 18,
    credentialsInputFontSize: 19,
    credentialsBtnBorderRadius: 16,
    credentialsBtnPaddingV: 18,
    credentialsBtnFontSize: 19,

    // Email linked row
    emailLinkedRowBorderRadius: 16,
    emailLinkedRowPadding: 16,
    emailLinkedRowGap: 16,
    emailLinkedBadgeSize: 44,
    emailLinkedBadgeBorderRadius: 22,
    emailLinkedIconFontSize: 20,
    emailLinkedLabelFontSize: 14,
    emailLinkedValueFontSize: 18,

    // Logout
    logoutMarginH: 28,
    logoutMarginTop: 12,
    logoutPaddingV: 22,
    logoutBorderRadius: 22,
    logoutIconFontSize: 24,
    logoutTextFontSize: 20,
    logoutGap: 14,

    // Modal
    modalOverlayPadding: 28,
    modalBorderRadius: 32,
    modalPadding: 34,
    modalMaxWidth: 600,
    modalTitleFontSize: 34,
    modalTitleMarginBottom: 32,
    modalLabelFontSize: 20,
    modalLabelMarginBottom: 12,
    modalInputBorderRadius: 16,
    modalInputPadding: 20,
    modalInputFontSize: 20,
    modalInputGroupMarginBottom: 28,

    // Age buttons
    ageBtnSize: 58,
    ageBtnBorderRadius: 30,
    ageBtnFontSize: 22,
    ageSectionGap: 16,
    ageSectionMarginTop: 14,

    // Gender buttons
    genderBtnBorderRadius: 30,
    genderBtnPaddingV: 36,
    genderEmojiFontSize: 70,
    genderLabelFontSize: 32,
    genderSectionGap: 28,
    genderSectionMarginTop: 14,

    // Modal actions
    modalActionGap: 14,
    modalActionMarginTop: 28,
    actionBtnPaddingV: 20,
    actionBtnBorderRadius: 16,
    actionBtnFontSize: 20,
  },
  // ── Billing screens ───────────────────────────────────────
  billing: {
    headerPaddingH: 26,
    headerPaddingBottom: 20,
    backBtnSize: 52,
    backBtnBorderRadius: 26,
    backIconFontSize: 24,
    titleFontSize: 24,
    subtitleFontSize: 16,

    scrollPadding: 26,
    scrollPaddingTop: 28,

    // Plan card
    planCardBorderRadius: 28,
    planCardPadding: 26,
    planCardMarginBottom: 28,
    planLabelFontSize: 13,
    planNameFontSize: 36,
    planPriceFontSize: 20,
    statusBadgeBorderRadius: 14,
    statusBadgePaddingH: 14,
    statusBadgePaddingV: 6,
    statusTextFontSize: 14,
    nextBillingFontSize: 16,
    upgradeBtnBorderRadius: 16,
    upgradeBtnPaddingV: 16,
    upgradeBtnFontSize: 18,

    // Section cards
    sectionBorderRadius: 22,
    sectionPadding: 22,
    sectionMarginBottom: 22,
    sectionTitleFontSize: 17,
    sectionLinkFontSize: 16,

    // Card chip
    cardChipWidth: 60,
    cardChipHeight: 40,
    cardChipBorderRadius: 9,
    cardChipFontSize: 11,
    cardNumFontSize: 18,
    cardExpFontSize: 14,
    defaultBadgeFontSize: 13,
    defaultBadgeBorderRadius: 11,
    defaultBadgePaddingH: 12,
    defaultBadgePaddingV: 5,

    addCardBtnPaddingV: 20,
    addCardBtnBorderRadius: 16,
    addCardFontSize: 17,

    historyHintFontSize: 16,
    historyHintBorderRadius: 14,
    historyHintPadding: 16,

    // Subscription plans screen
    planCardWidth: 0.72,
    planCardMargin: 20,
    planCardBorderRadius2: 36,
    planCardPaddingH: 28,
    planCardPaddingTop: 36,
    planCardPaddingBottom: 34,
    planIconWrapperSize: 152,
    planIconOuterRing: 152,
    planIconInnerRing: 114,
    planIconCircle: 86,
    planIconEmojiFontSize: 38,
    planNameFontSize2: 34,
    planTaglineFontSize: 17,
    planDescFontSize: 15,
    planDescLineHeight: 23,
    planPriceMainFontSize: 46,
    planPriceSubFontSize: 18,
    planPriceBorderRadius: 22,
    planPricePaddingV: 14,
    planPricePaddingH: 30,
    featureRowBorderRadius: 16,
    featureRowPaddingV: 12,
    featureRowPaddingH: 16,
    featureRowMarginBottom: 8,
    featureIconWrapSize: 40,
    featureIconFontSize: 18,
    featureLabelFontSize: 15,
    featureCheckFontSize: 15,
    ctaBtnHeight: 68,
    ctaBtnBorderRadius: 34,
    ctaEmojiFontSize: 22,
    ctaTextFontSize: 19,
    currentPlanBadgeBorderRadius: 14,
    currentPlanBadgePaddingH: 20,
    currentPlanBadgePaddingV: 8,
    currentPlanBadgeFontSize: 14,
    currentPlanBadgeMarginBottom: 16,
    trialNoteFontSize: 14,
    swipeHintFontSize: 15,
    cycleToggleBorderRadius: 24,
    cycleTogglePillBorderRadius: 18,
    cycleTogglePillPaddingV: 15,
    cycleToggleFontSize: 15,
    cycleBadgeFontSize: 11,
    paginationDotSize: 8,
    paginationDotActiveWidth: 30,

    // Payment method screen
    cardItemBorderRadius: 22,
    cardItemPadding: 22,
    cardItemMarginBottom: 16,
    menuBtnSize: 44,
    menuDotsFontSize: 28,
    actionItemPaddingV: 16,
    actionItemPaddingH: 20,
    actionItemFontSize: 17,
    addMethodBtnBorderRadius: 20,
    addMethodBtnPaddingV: 22,
    addMethodIconFontSize: 28,
    addMethodFontSize: 18,

    // Add card modal
    modalSheetBorderRadius: 32,
    modalSheetPadding: 34,
    modalSheetTitleFontSize: 24,
    modalSheetSubtitleFontSize: 16,
    modalSheetLabelFontSize: 14,
    modalSheetInputBorderRadius: 16,
    modalSheetInputPadding: 20,
    modalSheetInputFontSize: 19,
    modalSheetBrandBtnPaddingH: 20,
    modalSheetBrandBtnPaddingV: 12,
    modalSheetBrandBtnBorderRadius: 14,
    modalSheetBrandFontSize: 16,
    modalSheetActionPaddingV: 20,
    modalSheetActionBorderRadius: 16,
    modalSheetActionFontSize: 18,
    modalHandleWidth: 56,
    modalHandleHeight: 5,

    // Billing history
    summaryCardBorderRadius: 22,
    summaryCardPadding: 22,
    summaryCardMarginBottom: 28,
    summaryValFontSize: 24,
    summaryLblFontSize: 12,
    listCardBorderRadius: 22,
    listCardPadding: 22,
    listLabelFontSize: 14,
    invoiceRowPaddingV: 20,
    invoiceRowGap: 16,
    invoiceDateFontSize: 14,
    invoiceDescFontSize: 17,
    invoiceAmountFontSize: 20,
    statusBadgeRowPaddingH: 12,
    statusBadgeRowPaddingV: 4,
    statusBadgeRowBorderRadius: 10,
    statusBadgeRowFontSize: 12,
    downloadLinkFontSize: 13,
    emptyIconFontSize: 68,
    emptyTitleFontSize: 24,
    emptySubtitleFontSize: 17,

    // ── BillingHistoryScreen ─────────────────────
    historyHeaderPaddingH: 26,
    historyHeaderPaddingBottom: 20,
    historyBackBtnSize: 52,
    historyBackBtnBorderRadius: 26,
    historyBackIconFontSize: 24,
    historyTitleFontSize: 24,
    historyScrollPadding: 26,
    historySummaryCardBorderRadius: 22,
    historySummaryCardPadding: 22,
    historySummaryCardMarginBottom: 28,
    historySummaryValFontSize: 26,
    historySummaryLblFontSize: 13,
    historyListCardBorderRadius: 22,
    historyListCardPadding: 22,
    historyListLabelFontSize: 14,
    historyRowPaddingV: 20,
    historyRowGap: 16,
    historyDateFontSize: 14,
    historyDescFontSize: 17,
    historyAmountFontSize: 20,
    historyStatusBadgePaddingH: 12,
    historyStatusBadgePaddingV: 4,
    historyStatusBadgeBorderRadius: 10,
    historyStatusFontSize: 12,
    historyDownloadFontSize: 13,
    historyEmptyPaddingV: 80,
    historyEmptyIconFontSize: 68,
    historyEmptyTitleFontSize: 24,
    historyEmptySubFontSize: 17,

    // ── LevelSelectScreen ────────────────────────
    levelHeaderPaddingH: 26,
    levelHeaderPaddingBottom: 22,
    levelBackBtnSize: 52,
    levelBackBtnBorderRadius: 26,
    levelBackIconFontSize: 24,
    levelHeaderTitleFontSize: 24,
    levelScrollPadding: 28,
    levelIntroBoxBorderRadius: 24,
    levelIntroBoxPadding: 28,
    levelIntroBoxMarginBottom: 32,
    levelIntroBoxGap: 12,
    levelIntroEmojiFontSize: 56,
    levelIntroTitleFontSize: 24,
    levelIntroTitleLineHeight: 34,
    levelIntroSubFontSize: 16,
    levelIntroSubLineHeight: 25,
    levelGridGap: 14,
    levelGridMarginBottom: 28,
    levelCardBorderRadius: 20,
    levelCardNumberFontSize: 32,
    levelSelectedDotSize: 10,
    levelSelectedDotBorderRadius: 5,
    levelCalloutBorderRadius: 22,
    levelCalloutPadding: 22,
    levelCalloutMarginBottom: 32,
    levelCalloutGap: 6,
    levelCalloutLabelFontSize: 13,
    levelCalloutLevelFontSize: 58,
    levelCalloutLevelLineHeight: 68,
    levelCalloutDescFontSize: 17,
    levelConfirmBtnHeight: 70,
    levelConfirmBtnBorderRadius: 35,
    levelConfirmTextFontSize: 22,

    // ── PaymentMethodScreen ──────────────────────
    paymentCardBorderRadius: 22,
    paymentCardPadding: 22,
    paymentCardMarginBottom: 16,
    paymentChipWidth: 60,
    paymentChipHeight: 40,
    paymentChipBorderRadius: 9,
    paymentChipFontSize: 11,
    paymentCardNumFontSize: 18,
    paymentCardExpFontSize: 14,
    paymentMenuBtnSize: 44,
    paymentMenuDotsFontSize: 28,
    paymentDefaultBadgeBorderRadius: 11,
    paymentDefaultBadgePaddingH: 14,
    paymentDefaultBadgePaddingV: 5,
    paymentDefaultBadgeFontSize: 13,
    paymentActionMenuBorderRadius: 14,
    paymentActionItemPaddingV: 16,
    paymentActionItemPaddingH: 20,
    paymentActionItemFontSize: 17,
    paymentAddBtnBorderRadius: 20,
    paymentAddBtnPaddingV: 22,
    paymentAddBtnIconFontSize: 28,
    paymentAddBtnFontSize: 18,
    paymentEmptyPaddingV: 68,
    paymentEmptyIconFontSize: 68,
    paymentEmptyTitleFontSize: 24,
    paymentEmptySubFontSize: 17,
    // Add card modal
    paymentModalHandleWidth: 56,
    paymentModalHandleHeight: 5,
    paymentModalBorderRadius: 32,
    paymentModalPadding: 34,
    paymentModalTitleFontSize: 24,
    paymentModalSubFontSize: 16,
    paymentModalLabelFontSize: 14,
    paymentModalInputBorderRadius: 16,
    paymentModalInputPadding: 20,
    paymentModalInputFontSize: 19,
    paymentModalBrandBtnPaddingH: 20,
    paymentModalBrandBtnPaddingV: 12,
    paymentModalBrandBtnBorderRadius: 14,
    paymentModalBrandFontSize: 16,
    paymentModalActionPaddingV: 20,
    paymentModalActionBorderRadius: 16,
    paymentModalActionFontSize: 18,

    // ── PurchaseScreen ───────────────────────────
    purchaseHeaderPaddingH: 26,
    purchaseHeaderPaddingBottom: 22,
    purchaseBackBtnSize: 52,
    purchaseBackBtnBorderRadius: 26,
    purchaseBackIconFontSize: 24,
    purchaseHeaderTitleFontSize: 24,
    purchaseScrollPadding: 28,
    purchaseSectionLabelFontSize: 17,
    purchaseSectionLabelMarginBottom: 14,
    purchaseOrderCardBorderRadius: 28,
    purchaseOrderCardPadding: 26,
    purchaseOrderCardMarginBottom: 32,
    purchasePlanIconSize: 72,
    purchasePlanIconBorderRadius: 36,
    purchasePlanIconEmojiFontSize: 34,
    purchasePlanNameFontSize: 28,
    purchasePlanTaglineFontSize: 16,
    purchasePlanDescFontSize: 15,
    purchasePlanDescLineHeight: 24,
    purchasePricePillBorderRadius: 16,
    purchasePricePillPaddingV: 12,
    purchasePricePillPaddingH: 22,
    purchasePriceAmountFontSize: 40,
    purchasePriceCycleFontSize: 17,
    purchaseFeatureCheckFontSize: 17,
    purchaseFeatureLabelFontSize: 15,
    purchaseFeatureRowGap: 12,
    purchaseFeatureRowMarginBottom: 8,
    purchaseNoCardBorderRadius: 22,
    purchaseNoCardPadding: 34,
    purchaseNoCardGap: 12,
    purchaseNoCardIconFontSize: 56,
    purchaseNoCardTitleFontSize: 22,
    purchaseNoCardSubFontSize: 17,
    purchaseAddCardBtnBorderRadius: 16,
    purchaseAddCardBtnPaddingH: 40,
    purchaseAddCardBtnPaddingV: 16,
    purchaseAddCardBtnFontSize: 18,
    purchaseCardListBorderRadius: 22,
    purchaseCardRowPadding: 22,
    purchaseRadioSize: 28,
    purchaseRadioInnerSize: 14,
    purchaseCardNumFontSize: 18,
    purchaseCardExpFontSize: 14,
    purchaseDefaultBadgeBorderRadius: 11,
    purchaseDefaultBadgePaddingH: 12,
    purchaseDefaultBadgePaddingV: 5,
    purchaseDefaultBadgeFontSize: 13,
    purchaseAddAnotherPaddingV: 20,
    purchaseAddAnotherFontSize: 17,
    purchaseTotalCardBorderRadius: 20,
    purchaseTotalCardPadding: 22,
    purchaseTotalCardMarginBottom: 16,
    purchaseTotalLabelFontSize: 20,
    purchaseTotalAmountFontSize: 36,
    purchaseTotalCycleFontSize: 14,
    purchasePolicyFontSize: 14,
    purchasePolicyLineHeight: 24,
    purchasePolicyMarginBottom: 32,
    purchaseCheckoutBtnHeight: 72,
    purchaseCheckoutBtnBorderRadius: 36,
    purchaseCheckoutEmojiFontSize: 24,
    purchaseCheckoutTextFontSize: 22,
    // Add card sheet
    purchaseSheetBorderRadius: 32,
    purchaseSheetPadding: 34,
    purchaseSheetTitleFontSize: 24,
    purchaseSheetSubFontSize: 16,
    purchaseSheetLabelFontSize: 14,
    purchaseSheetInputBorderRadius: 16,
    purchaseSheetInputPadding: 20,
    purchaseSheetInputFontSize: 19,
    purchaseSheetBrandPaddingH: 20,
    purchaseSheetBrandPaddingV: 12,
    purchaseSheetBrandBorderRadius: 14,
    purchaseSheetBrandFontSize: 16,
    purchaseSheetActionPaddingV: 20,
    purchaseSheetActionBorderRadius: 16,
    purchaseSheetActionFontSize: 18,
    purchaseSheetHandleWidth: 56,
    purchaseSheetHandleHeight: 5,
  },

  // ── Learning Path screen ──────────────────────────────────
  learningPath: {
    cardWidth: 0.38,
    cardHeight: 210,
    connectorHeight: 80,
    screenPad: 24,

    // Card internals
    cardBorderRadius: 24,
    cardPaddingTop: 16,
    cardPaddingH: 16,
    cardPaddingBottom: 14,
    lvlBadgeSize: 46,
    lvlBadgeBorderRadius: 14,
    lvlNumFontSize: 20,
    emojiFontSize: 28,
    gradeFontSize: 16,
    gradeLineHeight: 22,
    gradeMarginBottom: 6,
    statFontSize: 13,
    statMarginBottom: 7,
    skillFontSize: 13,
    skillLineHeight: 18,
    youBadgeBorderRadius: 8,
    youBadgePaddingV: 6,
    youTxtFontSize: 11,
    youTxtLetterSpacing: 1.5,

    // Header
    backBtnSize: 52,
    backBtnBorderRadius: 26,
    backIconFontSize: 24,
    titleFontSize: 26,
    subtitleFontSize: 14,
    lvlPillBorderRadius: 14,
    lvlPillPaddingH: 16,
    lvlPillPaddingV: 8,
    lvlPillFontSize: 14,

    // Strip
    stripPaddingV: 14,
    stripValFontSize: 20,
    stripLblFontSize: 12,
    stripDivHeight: 36,

    // End cap
    endCapPaddingV: 40,
    endCapFontSize: 16,
  },

  // ── Reports screen ────────────────────────────────────────
  reports: {
    scrollPaddingH: 24,
    scrollPaddingBottom: 32,

    // Top bar
    topBarPaddingH: 20,
    topBarPaddingBottom: 16,
    backBtnSize: 52,
    backBtnBorderRadius: 26,
    topTitleFontSize: 22,

    // Child header
    childAvatarSize: 72,
    childAvatarBorderRadius: 36,
    childAvatarFontSize: 30,
    childNameFontSize: 28,
    childLevelFontSize: 16,
    childHeaderGap: 20,
    childHeaderMarginBottom: 28,

    // Stat pills
    pillBorderRadius: 22,
    pillPaddingV: 20,
    pillPaddingH: 10,
    pillGap: 6,
    pillRowGap: 12,
    pillRowMarginBottom: 20,
    pillEmojiFontSize: 28,
    pillValueFontSize: 26,
    pillLabelFontSize: 12,

    // Section card
    sectionCardBorderRadius: 28,
    sectionCardPadding: 26,
    sectionCardMarginBottom: 20,
    sectionIconFontSize: 24,
    sectionTitleFontSize: 20,
    sectionHeaderGap: 12,
    sectionHeaderMarginBottom: 22,

    // Ring chart
    ringChartSize: 200,
    ringLegendPaddingLeft: 26,
    ringLegendGap: 20,
    legendDotSize: 14,
    legendLabelFontSize: 14,
    legendValueFontSize: 17,

    // Weekly bar chart
    barChartHeight: 130,
    barCountFontSize: 13,
    barWeekLabelFontSize: 12,

    // Skill bars
    skillIconSize: 36,
    skillLabelFontSize: 17,
    skillPctFontSize: 17,
    skillTrackHeight: 11,
    skillRowGap: 16,
    skillRowMarginBottom: 22,

    // Story rows
    statusDotSize: 11,
    storyTitleFontSize: 17,
    storyDateFontSize: 14,
    storyDotSize: 14,
    storyDotGap: 7,
    storyRowGap: 16,
    storyRowPaddingV: 16,

    // Chart subtitle
    chartSubFontSize: 14,
    chartSubMarginBottom: 16,

    // Story legend
    storyLegendGap: 20,
    storyLegendItemGap: 7,
    storyLegendDotSize: 11,

    // Loading / empty states
    loadingEmojiFontSize: 64,
    loadingTextFontSize: 20,
    retryBtnBorderRadius: 16,
    retryBtnPaddingH: 34,
    retryBtnPaddingV: 14,
    retryTextFontSize: 18,
    emptyEmojiFontSize: 72,
    emptyTitleFontSize: 28,
    emptyTextFontSize: 18,
    emptyTextLineHeight: 28,
    emptyWrapPaddingV: 80,
    emptyWrapGap: 16,
  },
};
